### ISSUE TITLE
Periodic: skr-aws-upgrade-integration-dev

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#5523]
**Description**
Job is failing for a week: 42 executions, 100% failure rate
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/skr-aws-upgrade-integration-dev

**Expected result**

Fix or delete the job if not needed.

**Comment by Sawthis** [comment]
Periodic [skr-aws-upgrade-integration-dev](https://status.build.kyma-project.io/?type=periodic&job=skr-aws-upgrade-integration-dev) job failed 4 times in last 24h counting from 14.06.2022 2PM.

**Comment by Sawthis** [comment]
https://github.com/kyma-project/kyma/issues/14386

**Comment by Sawthis** [comment]
Periodic [skr-aws-upgrade-integration-dev](https://status.build.kyma-project.io/?type=periodic&job=skr-aws-upgrade-integration-dev) job failed 4 times in last 24h counting from 15.06.2022 11AM.

**Comment by arturskorupa** [comment]
All executions failed with the same set of errors:

```
6 passing (43m)
  16 failing

  1) SKR-Upgrade-test
       Provision SKR with ID 57bceeaf-3f88-4acb-95fb-56c62ce75783:
     Error: unable to verify the first certificate
      at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
      at TLSSocket._finishInit (_tls_wrap.js:937:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)

  2) SKR-Upgrade-test
       Should save kubeconfig for the SKR to ~/.kube/config:
     TypeError: Cannot read property 'shoot' of undefined
      at Context.<anonymous> (skr-aws-upgrade-integration/index.js:149:30)
      at processImmediate (internal/timers.js:464:21)

  3) SKR-Upgrade-test
       Should initialize K8s client:
     TypeError: Cannot read property 'shoot' of undefined
      at Context.<anonymous> (skr-aws-upgrade-integration/index.js:153:48)
      at processImmediate (internal/timers.js:464:21)

  4) SKR-Upgrade-test
       Assign SKR to scenario:
     TypeError: Cannot read property 'shoot' of undefined
      at Context.<anonymous> (skr-aws-upgrade-integration/index.js:162:49)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

  5) SKR-Upgrade-test
       CommerceMock test fixture should be ready:
     Failed to fetch resource metadata for v1/Namespace: connect ECONNREFUSED 127.0.0.1:8080
  Error: connect ECONNREFUSED 127.0.0.1:8080
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)

  6) SKR-Upgrade-test
       Listing all pods in cluster:
     Error: connect ECONNREFUSED 127.0.0.1:8080
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)

  7) SKR-Upgrade-test
       in-cluster event should be delivered:
     Error: Wait for VirtualService lastorder timeout (20000 ms)
      at Timeout._onTimeout (utils/index.js:337:20)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  8) SKR-Upgrade-test
       function should be reachable through secured API Rule:
     Error: Wait for VirtualService commerce-mock timeout (20000 ms)
      at Timeout._onTimeout (utils/index.js:337:20)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  9) SKR-Upgrade-test
       order.created.v1 legacy event should trigger the lastorder function:
     Error: Wait for VirtualService commerce-mock timeout (20000 ms)
      at Timeout._onTimeout (utils/index.js:337:20)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  10) SKR-Upgrade-test
       Should print report of restarted containers, skipped if no crashes happened:
     Error: connect ECONNREFUSED 127.0.0.1:8080
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)

  11) SKR-Upgrade-test
       Listing all pods in cluster:
     Error: connect ECONNREFUSED 127.0.0.1:8080
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)

  12) SKR-Upgrade-test
       in-cluster event should be delivered:
     Error: Wait for VirtualService lastorder timeout (20000 ms)
      at Timeout._onTimeout (utils/index.js:337:20)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  13) SKR-Upgrade-test
       function should be reachable through secured API Rule:
     Error: Wait for VirtualService commerce-mock timeout (20000 ms)
      at Timeout._onTimeout (utils/index.js:337:20)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  14) SKR-Upgrade-test
       order.created.v1 legacy event should trigger the lastorder function:
     Error: Wait for VirtualService commerce-mock timeout (20000 ms)
      at Timeout._onTimeout (utils/index.js:337:20)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  15) SKR-Upgrade-test
       Should print report of restarted containers, skipped if no crashes happened:
     Error: connect ECONNREFUSED 127.0.0.1:8080
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)

  16) SKR-Upgrade-test
       Test fixtures should be deleted:
     Error: connect ECONNREFUSED 127.0.0.1:8080
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
```

**Comment by varbanv** [comment]
Closing due to the original failure cause was fixed. New ticket will be opened for latest pipeline failures.
