### ISSUE TITLE
Failing skr-azure-integration-dev

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#5582]
skr-azure-integration-dev job is failing from May 27th 
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/skr-azure-integration-dev?buildId=
```
     Error: Provisioning failed: Error: Error when updating label definition with key scenarios: Error: Error calling Director API: 422 Unprocessable Entity
      at provisionSKRInstance (skr-test/provision/provision-skr.js:37:11)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (skr-test/test.js:53:15)
```

**Expected result**

Fix or delete the job if not needed.

**Comment by tillknuesting** [comment]
resolved
